// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCelAjPZ6zSujfIi_V2K5FX2_XV8ILIMsk',
    appId: '1:467697098105:web:a8ef7c2243179f1b6c23a8',
    messagingSenderId: '467697098105',
    projectId: 'drivora-adas',
    authDomain: 'drivora-adas.firebaseapp.com',
    storageBucket: 'drivora-adas.firebasestorage.app',
    measurementId: 'G-MPVH5J3XWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCelAjPZ6zSujfIi_V2K5FX2_XV8ILIMsk',
    appId: '1:467697098105:android:eeceaee72e85cd026c23a8',
    messagingSenderId: '467697098105',
    projectId: 'drivora-adas',
    storageBucket: 'drivora-adas.firebasestorage.app',
  );
}
